# Generated by Django 3.2.5 on 2021-07-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(0, '9x9'), (1, '16x16'), (2, '30x16')], max_length=5)),
                ('end_game', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='core.boardmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SquareItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_mines', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_mine', models.BooleanField(default=False)),
                ('is_flaged', models.BooleanField(default=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_items', to='core.rowmodel')),
            ],
        ),
    ]
