# Generated by Django 3.2.5 on 2021-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowmodel',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squareitemmodel',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
