# Generated by Django 3.2.5 on 2021-07-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210723_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowmodel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.boardmodel'),
        ),
    ]
