# Generated by Django 3.2.5 on 2021-07-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rowmodel_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='squareitemmodel',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='square_items', to='core.boardmodel'),
        ),
    ]
