# Generated by Django 3.2.5 on 2021-07-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boardmodel_square_remaining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowmodel',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='squareitemmodel',
            options={'ordering': ['index']},
        ),
    ]
