# Generated by Django 3.2.5 on 2021-07-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210725_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='level',
            field=models.IntegerField(choices=[(0, '9x9'), (1, '16x16'), (2, '30x16')], max_length=5),
        ),
    ]
