# Generated by Django 3.2.5 on 2021-07-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_boardmodel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='level',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='cols_number',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='mines_number',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='rows_number',
            field=models.IntegerField(default=9),
        ),
    ]
