# Generated by Django 3.2.5 on 2021-07-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boardmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
