# Generated by Django 3.2.5 on 2021-07-27 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_boardmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
