# Generated by Django 3.2.5 on 2021-07-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210727_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
