version: '3'

services:

    nginx:
        container_name: server_nginx
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - static_volume:/code/static
        depends_on:
            - backend_api
        ports:
            - 80:80
            - 8000:8000

    db_postgres:
        image: postgres
        container_name: postgres_db_api
        environment:
            POSTGRES_USER: minesweeper
            POSTGRES_DB: minesweeper
            POSTGRES_PASSWORD: minesweeper
        ports:
            - "5432:5432"
            
    backend_api:
        build: .
        command: bash -c "python manage.py collectstatic --noinput &&
                          python manage.py migrate && 
                          uwsgi --socket :8001 --module minesweeper.wsgi --py-autoreload=1"
        container_name: server
        env_file: 
            - envs/local.env
        volumes:
            - .:/code
            - static_volume:/code/static
        expose:
            - "80"
        depends_on:
            - db_postgres

volumes:
    static_volume:
